// SPDX-License-Identifier: Apache-2.0
import Foundation

/// Pure `ProxyConfig → PAC script` builder. Paired with `LocalPACServer` to
/// serve the script at `http://<localHost>:<localPACPort>/proxy.pac` so
/// Chromium-based clients (Edge, Chrome, Arc) get a proxy decision even when
/// the upstream corporate PAC URL is unreachable (VPN off, captive portal,
/// corporate DNS flap — the failure mode that manifests as Chromium's
/// `ERR_TUNNEL_CONNECTION_FAILED`).
///
/// ## What the emitted script decides
///
/// For each `(url, host)` tuple:
///
/// - If `host` matches any `forceProxyHosts` pattern → `PROXY <localHost>:<localPort>`
///   (no DIRECT fallback — forceProxy is "this host MUST go through the proxy").
/// - Else if `host` matches any `noProxyHosts` pattern → `DIRECT`.
/// - Otherwise → `PROXY <localHost>:<localPort>` in strict mode, or
///   `PROXY <localHost>:<localPort>; DIRECT` outside strict mode. Strict mode
///   is for corporate VPNs where internal DNS cannot resolve public internet
///   names; browser-side DIRECT fallback would only create DNS failures.
///
/// This matches the bypass decision `HTTPProxyHandler.channelRead` already
/// makes at request time (see `NoProxyMatcher.shouldBypass`), except the
/// direct-routing / `cachedDirectReachable` branches aren't modeled — those are
/// runtime probe outcomes that PAC (a pure function of url+host) can't know.
/// Normal mode routes through the local proxy first. Only unconditional
/// direct-routing states (VPN off, no upstreams configured) emit a `DIRECT`-only
/// PAC. On VPN reassertion or probe failures, PAC-honoring clients keep sending
/// traffic to Conduit so Chromium/Edge do not resolve split-DNS names with
/// their browser DNS stack.
///
/// ## Pattern semantics
///
/// The emitted `matchesAny(host, patterns)` helper is a line-for-line port of
/// `NoProxyMatcher.matchesAny` — exact, leading-dot, `*.`-prefix, trailing-`.*`,
/// and trailing-`*` patterns, case-insensitive, whitespace-trimmed. The
/// `PACScriptEmitterTests.testParity*` cases lock the two implementations
/// together against a representative corpus.
///
/// ## Why not use PAC's built-in helpers (`dnsDomainIs`, `shExpMatch`)?
///
/// Those exist and are cheaper to emit, but `NoProxyMatcher`'s semantics
/// don't map 1:1 — e.g. `*.example.com` in our matcher matches both
/// `sub.example.com` and the apex `example.com`, while `shExpMatch("*.example
/// .com")` rejects the apex. Porting the matcher verbatim is one extra
/// function in the emitted script (~25 lines) and removes the parity
/// surprise. See `docs/design-local-pac-serving.md` when that lands.
package enum PACScriptEmitter {

    /// Emit the PAC script for this config. The script is a self-contained
    /// JavaScript string, safe to serve as-is with content type
    /// `application/x-ns-proxy-autoconfig`. Not cached at this layer — callers
    /// can hash the result to implement ETag / conditional-GET at the
    /// serving layer.
    package static func script(for config: ProxyConfig, directRoutingAllowed: Bool = false) -> String {
        // Pre-normalize patterns at emit time (trim + lowercase) to match
        // NoProxyMatcher's lazy normalization. Empty entries are dropped so
        // the emitted `matchesAny` doesn't waste cycles on them.
        let forcePatterns = normalize(config.forceProxyHosts)
        let noProxyPatterns = normalize(config.noProxyHosts)
        let proxyDirective = "PROXY \(config.localHost):\(config.localPort)"
        let profile = config.profileName.isEmpty ? "default" : config.profileName

        var lines: [String] = []
        lines.reserveCapacity(48)

        // Header comment — useful when an IT admin inspects the served PAC
        // (curl http://127.0.0.1:<port>/proxy.pac) to debug routing.
        lines.append("// Generated by Conduit. DO NOT EDIT — regenerated on every")
        lines.append("// config reload. Served by LocalPACServer at /proxy.pac.")
        lines.append("// Profile: \(jsComment(profile))")
        lines.append("// Proxy:   \(jsComment("\(config.localHost):\(config.localPort)"))")
        lines.append("// forceProxyHosts: \(forcePatterns.count), noProxyHosts: \(noProxyPatterns.count)")
        lines.append("")

        if directRoutingAllowed {
            lines.append("function FindProxyForURL(url, host) {")
            lines.append("  return \"DIRECT\";")
            lines.append("}")
            return lines.joined(separator: "\n") + "\n"
        }

        lines.append("function FindProxyForURL(url, host) {")
        lines.append("  host = (host || \"\").toLowerCase();")
        lines.append("")
        lines.append("  var forceProxy = \(emitStringArray(forcePatterns));")
        lines.append("  var noProxy = \(emitStringArray(noProxyPatterns));")
        lines.append("")
        lines.append("  if (matchesAny(host, forceProxy)) {")
        lines.append("    return \(jsStringLiteral(proxyDirective));")
        lines.append("  }")
        lines.append("  if (matchesAny(host, noProxy)) {")
        lines.append("    return \"DIRECT\";")
        lines.append("  }")
        let defaultDirective = config.strictMode ? proxyDirective : proxyDirective + "; DIRECT"
        lines.append("  return \(jsStringLiteral(defaultDirective));")
        lines.append("}")
        lines.append("")
        lines.append(matchesAnyFunction)

        return lines.joined(separator: "\n") + "\n"
    }

    // MARK: - Matcher function (verbatim port of NoProxyMatcher.matchesAny)

    /// The JS helper. Emitted once per script. Kept as a single string
    /// constant (not built line-by-line) so diff churn from whitespace
    /// tweaks only touches this one place; the golden test pins its bytes.
    private static let matchesAnyFunction: String = """
    // Mirrors Sources/ProxyKernel/Proxy/NoProxyMatcher.swift matchesAny.
    // Patterns are pre-normalized (trimmed + lowercased) at emit time; this
    // helper just runs the five match cases against a lowercased host.
    function matchesAny(host, patterns) {
      for (var i = 0; i < patterns.length; i++) {
        var pat = patterns[i];
        if (pat.length === 0) continue;
        if (pat === host) return true;
        if (pat.length >= 2 && pat.substring(0, 2) === "*.") {
          var suffix = pat.substring(1);
          if (host.length >= suffix.length &&
              host.substring(host.length - suffix.length) === suffix) return true;
          if (host === pat.substring(2)) return true;
        }
        if (pat.charAt(0) === ".") {
          if (host.length >= pat.length &&
              host.substring(host.length - pat.length) === pat) return true;
          if (host === pat.substring(1)) return true;
        }
        if (pat.length >= 2 && pat.substring(pat.length - 2) === ".*") {
          var prefix = pat.substring(0, pat.length - 1);
          if (host.substring(0, prefix.length) === prefix) return true;
        }
        if (pat.length >= 1 && pat.charAt(pat.length - 1) === "*" &&
            !(pat.length >= 2 && pat.substring(pat.length - 2) === ".*")) {
          var prefix2 = pat.substring(0, pat.length - 1);
          if (host.substring(0, prefix2.length) === prefix2) return true;
        }
      }
      return false;
    }
    """

    // MARK: - Helpers

    private static func normalize(_ patterns: [String]) -> [String] {
        patterns
            .map { $0.trimmingCharacters(in: .whitespacesAndNewlines).lowercased() }
            .filter { !$0.isEmpty }
    }

    /// Emit a JS array literal. Inline for `<= 1` element; multi-line for
    /// readability when the list gets longer — matches the standard
    /// Chromium PAC files IT admins have seen before.
    private static func emitStringArray(_ values: [String]) -> String {
        if values.isEmpty { return "[]" }
        if values.count == 1 { return "[\(jsStringLiteral(values[0]))]" }
        let items = values.map { "    " + jsStringLiteral($0) }.joined(separator: ",\n")
        return "[\n\(items)\n  ]"
    }

    /// Escape a Swift `String` into a JS double-quoted string literal.
    /// Only the characters that can break JS string parsing are escaped;
    /// printable non-ASCII is passed through as UTF-8 (legal in JS source
    /// under any sensible encoding, and the emitted file is served with an
    /// explicit `charset=utf-8` by `LocalPACServer`).
    static func jsStringLiteral(_ value: String) -> String {
        var result = "\""
        result.reserveCapacity(value.count + 2)
        for scalar in value.unicodeScalars {
            switch scalar {
            case "\\": result += "\\\\"
            case "\"": result += "\\\""
            case "\n": result += "\\n"
            case "\r": result += "\\r"
            case "\t": result += "\\t"
            case "\u{0008}": result += "\\b"
            case "\u{000C}": result += "\\f"
            case "\u{0000}"..."\u{001F}", "\u{007F}":
                // Other ASCII control characters — emit as \uXXXX so the
                // JS parser sees a well-formed literal regardless of
                // transport encoding.
                result += String(format: "\\u%04X", scalar.value)
            default:
                result.unicodeScalars.append(scalar)
            }
        }
        result += "\""
        return result
    }

    /// Sanitize a string for embedding in a `// …` JS comment line. We strip
    /// anything that could break out of the comment (newlines, paragraph
    /// separators) and cap the length so a pathologically long profile name
    /// doesn't balloon the header. The script body is unaffected; only the
    /// informational header uses this.
    private static func jsComment(_ value: String) -> String {
        let oneLine = value
            .replacingOccurrences(of: "\r\n", with: " ")
            .replacingOccurrences(of: "\n", with: " ")
            .replacingOccurrences(of: "\r", with: " ")
            .replacingOccurrences(of: "\u{2028}", with: " ")
            .replacingOccurrences(of: "\u{2029}", with: " ")
        let capped = oneLine.count > 200 ? String(oneLine.prefix(200)) + "…" : oneLine
        return capped
    }
}
